### ISSUE TITLE
about dada2 filterandTrim parameter

### ISSUE THREAD

**Issue by chulghim** [ycl6/16S-rDNA-V3-V4#3]
Can i get  how to  determine dada2 filterAndTrim() paramer?
 (truncLen=c(240,230), minLen=200, maxN=0, truncQ=2, maxEE=c(2,5) ..)

For example:
 Illuminia MiSeq - (2*250bp reads) 
 321F: TAATTCGTCCTACGGRAGGCAG
 800R: AGCCGGACTACCRGGGTAT

I am curious if there is any formula.

**Comment by ycl6** [comment]
There isn't a formula I'm afriad. The paramter you would most likely need to alter from the default values is `truncLen`. You need to inspect the quality plot that you generate with `plotQualityProfile` to judge how many bases you would keep and at the same time not truncating the reads too much and end up unable to merge majority of the paired read, i.e. you need to have a general idea of what's the length distribution of your amplicons

**Comment by chulghim** [comment]
Thank you very much.
That's what i want to know.

Best regards, Namchul.

2020년 8월 10일 (월) 오후 5:19, I-Hsuan Lin <notifications@github.com>님이 작성:

**Comment by ycl6** [comment]
@chulghim Glad to help, I'll close this for now
