### ISSUE TITLE
downstream picrust2 analysis query

### ISSUE THREAD

**Issue by marwa38** [ycl6/16S-rDNA-V3-V4#5]
Hello I-Hsuan @ycl6 
Many thanks for this tutorial (https://ycl6.github.io/16S-Demo/4_picrust2_tutorial.html).
I was wondering if there is a possibility to draw a figure like this:
![image](https://user-images.githubusercontent.com/68851733/151612951-8fdb5232-ff40-4920-8a67-d99c2960c973.png)
Your help is much appreciated.

**Comment by ycl6** [comment]
Hi @marwa38 I suppose you can, by using `ggplot2` to visualise the result in a suitable format.

**Comment by cafferychen777** [comment]
@marwa38, I believe you can utilize ggpicrust2 for this purpose. It is a powerful R package specifically designed for creating visualizations related to picrust2 analysis. You can find the documentation and examples for ggpicrust2 [https://github.com/cafferychen777/ggpicrust2].

I hope this helps! Feel free to ask if you have any further questions. Thank you!
